spring:
  config:
    import: "optional:file:./.env[.properties]"
  application:
    name: ${APP_NAME:spring-boot-starter-0}
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/app_db?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&createDatabaseIfNotExist=true}
    username: ${DB_USERNAME:app_user}
    password: ${DB_PASSWORD:app_password}
  jpa:
    database-platform: ${JPA_DATABASE_PLATFORM:org.hibernate.dialect.MySQLDialect}
    show-sql: true

app:
  page:
    size: ${APP_PAGE_SIZE:10}

flyway:
  user: ${FLYWAY_USER:root}
  password: ${FLYWAY_PASSWORD:root}
